# I need to refer nodejs tasks in common folder
# catalogue is one role
# common is also another role
# I need to import a task nodejs.yaml in catalogue

- name: Install python
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: SetUp Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.command: pip3.6 install -r requirements.txt
  args:
    chdir: /app

- name: Start application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup